### PR TITLE
Database migrations

### PR DESCRIPTION
**Pull request by janosbrodbeck**
* `alembic.ini` is auto generated to 99% and should not be touched again
* `script.py.mako` is auto generated by alembic, don't want to touch it
* Our backend creates the database now only from migrations
* Initial migration is there, completely auto created from alembic
* Added a new test checking, whether the migrations create the newest schema 
(Getting the second db was a bit weird. It was now the best solution I came up with based on the postgre test library. I guess it could be easier / shorter, but dunno)

### CODE REVIEW

**Review by dolevi-tub — CHANGES_REQUESTED** [review]
This doesn't run for me. I use docker-compose up so it may that `getter.py` is not included in the build
```bash
Traceback (most recent call last):
  File "/usr/local/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/uvicorn/main.py", line 407, in main
    run(
  File "/usr/local/lib/python3.10/site-packages/uvicorn/main.py", line 573, in run
    server.run()
  File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/usr/local/lib/python3.10/site-packages/uvicorn/config.py", line 478, in load
    self.loaded_app = import_from_string(self.app)
  File "/usr/local/lib/python3.10/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/usr/local/lib/python3.10/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/./app/main.py", line 5, in <module>
    from app.db.init_db import init_db
  File "/./app/db/init_db.py", line 3, in <module>
    from getter import get_path
ModuleNotFoundError: No module named 'getter'
```

**Comment by janosbrodbeck** [comment]
Should be working now

**Review by dolevi-tub — CHANGES_REQUESTED** [review]
Could we add some `create *if exists*` to the database creation? Upon startup my backend container crashed instantly because it tried creating tables that already existed

**Comment by janosbrodbeck** [comment]
> Could we add some `create *if exists*` to the database creation? Upon startup my backend container crashed instantly because it tried creating tables that already existed

Yes, but it's effort. Honestly, this should be the last time you should need to do that. After that alembic creates a dedicated table to keep track of migrations

**Review by dolevi-tub — APPROVED** [review]
All good! :)

**Pull request merged**
